### ISSUE TITLE
Arrow functions in classes broken

### ISSUE THREAD

**Issue by icorbrey** [cmstead/js-refactor#114]
When attempting to convert a normal function into an arrow function inside a class, it goes from this:

```js
class Test
{
	test()
	{
		return ''
	}
}
```

To this:

```js
class Test
{
	test() => ''
}
```

Which is not the correct syntax. In addition, if any arrow functions are _already_ defined inside a class, the extension just straight up refuses to do anything, throwing an error "Unable to parse source code. Parser error: Unexpected token =". It also logs the following to the Remote Extension Host:

```
[2020-05-21 23:50:46.287] [exthost] [error] TypeError: parseSourceLines expected a value of type ast but got undefined of type undefined

JS Refactoring types are defined in the typeHelper file; more info can be found in type definitions.
	at throwEvaluationError (/home/icorbrey/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/node_modules/signet/bin/signet.js:154:19)
	at Object.<anonymous> (/home/icorbrey/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/node_modules/signet/bin/signet.js:283:17)
	at Object.enforceDecorator [as parseSourceLines] (/home/icorbrey/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/node_modules/signet/bin/signet.js:303:29)
	at /home/icorbrey/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/modules/commands/convertToArrowFunctionFactory.js:111:32
	at behavior (/home/icorbrey/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/modules/commands/commandDefFactory.js:26:82)
	at e._executeContributedCommand (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:648:894)
	at e.$executeContributedCommand (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:649:295)
	at e._doInvokeHandler (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:809:757)
	at e._invokeHandler (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:809:449)
	at e._receiveRequest (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:808:120)
	at e._receiveOneMessage (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:806:970)
	at /home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:805:213
	at e.fire (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:46:67)
	at v.fire (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:232:615)
	at /home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:978:179
	at e.fire (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:46:67)
	at v.fire (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:232:615)
	at t.PersistentProtocol._receiveMessage (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:237:17)
	at /home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:234:155
	at e.fire (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:46:67)
	at p.acceptChunk (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:230:129)
	at /home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:229:483
	at Socket.t (/home/icorbrey/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/out/vs/server/remoteExtensionHostProcess.js:238:565)
	at Socket.emit (events.js:200:13)
	at Socket.EventEmitter.emit (domain.js:471:20)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17) cmstead.jsRefactor.convertToArrowFunction
```

**Comment by cmstead** [comment]
Technically fields aren't part of the spec, so they aren't supported by my parser (AFAIK).

I will review the convert to arrow function behavior, but I fields are still experimental so there may be some lag time.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields

**Comment by icorbrey** [comment]
Any update on this? I don't use arrow fields any more so this no longer effects me, but just thought I'd follow up

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
