### ISSUE TITLE
Cannot extract template literal

### ISSUE THREAD

**Issue by CherryDT** [cmstead/js-refactor#126]
The thing I selected should be a valid source for the conversion, yet it fails with `Cannot read property '0' of undefined`:

```javascript
'/v1/account/accounts/' + cache.accountId + '/balance'
```

![image](https://user-images.githubusercontent.com/6010463/125198415-0ac09e00-e262-11eb-803b-7121a9c44718.png)

```
[2021-07-11 16:05:33.007] [exthost] [error] TypeError: Cannot read property '0' of undefined
    at Object.getSelectionCoords (/home/david/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/modules/shared/editor-tools/vsCodeHelperFactory.js:32:70)
    at /home/david/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/modules/commands/convertToTemplateLiteralFactory.js:89:56
    at behavior (/home/david/.vscode-server/extensions/cmstead.jsrefactor-2.20.6/modules/commands/commandDefFactory.js:26:82)
    at S._executeContributedCommand (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:120585)
    at S.$executeContributedCommand (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:84:121023)
    at u._doInvokeHandler (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:12743)
    at u._invokeHandler (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:12435)
    at u._receiveRequest (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:11097)
    at u._receiveOneMessage (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:9900)
    at /home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:88:8004
    at d.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
    at h.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:15777)
    at /home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:29793
    at d.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
    at h.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:15777)
    at r._receiveMessage (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:21035)
    at /home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:17921
    at d.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
    at c.acceptChunk (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:13138)
    at /home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:65:12486
    at d.fire (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:57:1726)
    at b._acceptChunk (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:19103)
    at /home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:15516
    at Socket._ (/home/david/.vscode-server/bin/2d23c42a936db1c7b3b06f918cde29561cc47cd6/out/vs/server/remoteExtensionHostProcess.js:103:13107)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) cmstead.jsRefactor.convertToTemplateLiteral
```

**Comment by cmstead** [comment]
I'm really sorry for taking so long to reply. I am closing up shop on JSR, BECAUSE there is a replacement tool. It's still under construction, but it should resolve the issue you are running into.

Marketplace:

https://marketplace.visualstudio.com/items?itemName=cmstead.js-codeformer

GitHub:

https://github.com/cmstead/js-codeformer
