### ISSUE TITLE
Unexpected Token ILLEGAL in js file with shebang

### ISSUE THREAD

**Issue by jamescodesthings** [cmstead/js-refactor#80]
Hey, I'm having trouble running any of the methods in JS Refactor. I've just noticed the reason is that the JS file starts with a shebang, and the parser must be trying to parse it: `#!/usr/bin/env node`.

I'm on OSX, vscode version `1.30.2`, JS Refactor:
```
Name: JS Refactor
Id: cmstead.jsrefactor
Description: Automated refactoring tools to smooth your development workflow
Version: 2.15.1
Publisher: Chris Stead
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=cmstead.jsrefactor
```

Whenever I try to run a JS Refactor method in the file I get:
```
[2019-01-29 07:54:55.098] [exthost] [info] ExtensionService#_doActivateExtension cmstead.jsrefactor {"startup":false,"activationEvent":"onCommand:cmstead.jsRefactor.extractMethod"}
[2019-01-29 07:54:55.098] [exthost] [info] ExtensionService#loadCommonJSModule /Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/extension
[2019-01-29 07:54:55.174] [exthost] [error] Error: Line 1: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:5020:27)
    at ErrorHandler.throwError (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:5027:21)
    at Scanner.throwUnexpectedToken (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:5155:35)
    at Scanner.scanPunctuator (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:5658:19)
    at Scanner.lex (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:6255:22)
    at JSXParser.Parser.nextToken (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:2079:34)
    at JSXParser.Parser (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:1916:15)
    at new JSXParser (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:463:24)
    at parse (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:117:19)
    at Object.parseModule (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/esprima/dist/esprima.js:139:13)
    at parse (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/modules/shared/ast-tools/parser.js:32:28)
    at Object.parseSourceLines (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/modules/shared/ast-tools/parser.js:18:16)
    at Object.<anonymous> (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/signet/bin/signet.js:244:29)
    at Object.enforceDecorator (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/node_modules/signet/bin/signet.js:276:29)
    at applyExtractMethod (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/modules/commands/extractMethodFactory.js:106:32)
    at module.exports (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/modules/commands/extractMethodFactory.js:146:17)
    at behavior (/Users/jamesm/.vscode/extensions/cmstead.jsrefactor-2.15.1/modules/commands/commandDefFactory.js:26:82)
    at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:501:455)
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:502:6)
    at t._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
    at t._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
    at t._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
    at t._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) cmstead.jsRefactor.extractMethod
```

With a pop up saying the method failed.

It would be useful if the parser fails to log the failure cause, it took me a moment to notice the shebang causing the issue. I'll remove it for now to get on with the extension, not sure if the actual problem is worth fixing.

**Comment by cmstead** [comment]
Thanks for submitting this. I noticed this a while ago, and I've been meaning to get to this issue. I'll see what I can do about fixing up the file before attempting to parse it.

**Comment by cmstead** [comment]
Shebang issue is tested and resolved. Fix will be available in the next release.

**Comment by cmstead** [comment]
https://github.com/cmstead/js-refactor/releases/tag/v2.15.5
